### ISSUE TITLE
dm-verity分析

### ISSUE THREAD

**Issue by chyyuu** [openthos/dmverify-analysis#1]
- [X] dmverity分析

**Comment by fengjinyang** [comment]
dm-verity的实现可在内核目录 .../drivers/md/dm-verity.c
dm-crypt的实现可在内核目录 .../drivers/md/dm-crypt.c，原理同dm-verity，不单独讲述

dm-verity将自己注册成device mapper的一个目标（target），并遵循这个体系向device mapper提供相关接口，其中 verity_ctr 用于提供关于摘要算法描述，verity_map则是验证的实现。

为了支持国产算法，我们只需要在调用verity_ctr处更替相应的国产算法即可。如果需要调整验证机制，则需要在verity_map处做些文章。目前看来，我们还不需要直接对dm-verity.c修修改改。

**Comment by fengjinyang** [comment]
这部分的问题主要是**如何让当前系统支持国产算法？**算法支持后，只需要在相应部位调用dm-verity的verity_ctr即可。

**Comment by fengjinyang** [comment]
## 关于 device mapper
- 逻辑设备到物理设备的映射机制（LVM 都是基于该机制实现）
- 内核中它通过一个个模块化的target driver插件实现对I/O请求的过滤或者重定向等工作
- 已经实现的插件包括软RAID，软加密等等
- 在内核中作为一个块设备驱动被注册
- 内核源码的 driver/md/ 目录
- 系统提供dmsetup命令，一般都是根据内核ioctl定义实现一套自己的函数库
