### ISSUE TITLE
rEFInd能否直接操作硬件？

### ISSUE THREAD

**Issue by fengjinyang** [openthos/dmverify-analysis#6]
我在rEFInd中扩展一些特性
现在有个访问硬件的需求，能不能不去单独实现驱动模块，直接访问？

**Comment by fengjinyang** [comment]
可以参考 UEFI与TPM 是如何处理的。谁可以提供相关代码，让我参考一下。

**Comment by chyyuu** [comment]
目前没人搞，需要你尽量自己解决了。

**Comment by fengjinyang** [comment]
《UEFI原理与编程》第7章前半部分里可以通过Protocol访问磁盘，理论上访问PCI设备也是没有问题的（先手头只有PCI形式的TCM模块）。第9章UEFI驱动以AC97（一种PCI设备）做演示，应该也有可以借鉴的地方。

**Comment by fengjinyang** [comment]
EDK2 中 SecurityPkg/Tcg 可能与TPM相关

**Comment by fengjinyang** [comment]
受到 http://www.cppblog.com/djxzh/archive/2011/10/02/157325.html 启发，现在可以访问PCI-TCM
1. 根据协议获取PCI的Controller
2. 遍历PCI设备，根据配置判断剔除Audio
